electronicarts/EASTL

- doc/EASTL Introduction.html
`Interent` → `Internet`
`commerical` → `commercial`
> Fix typos in Introduction

- CMakeLists.txt
CMake does not support compiler traits with the Intel compiler (used in the root CMakeLists.txt file for 'set_property(TARGET EASTL PROPERTY CXX_STANDARD 11)'), and the Intel compiler requires an explicit asm-block flag to build. This pull request checks if the build is executing on a Unix-based system with the Intel compiler, and adds flags to enable C++11 and asm-blocks. This enables successful builds on OS X Mavericks and Ubuntu 12.04 with Intel 16.0.1.
> Updated the CMake build system to work with Intel's compilers on Unix based systems, including OS X.

- CMakeLists.txt
- test/CMakeLists.txt
This will allow building EASTL separate from the tests.  Now EASTL can be used from a CMake project via `add_subdirectory(EASTL)`. The `test` folder became just an example of that.
I assumed `EASTL_THREAD_SUPPORT_AVAILABLE` is defined to `0` in the `test` build to allow the test code to use the EASTL thread support. Please tell if it's not true.
I ran two verbose builds to make sure the defines were correct.
Build in the root folder:
```
felipe@Felipes-MacBook-Pro:~/code/proto3d/EASTL (cmake-version *%)$ cmake -Bbuild -H. -DCMAKE_VERBOSE_MAKEFILE=ON && make -C build
-- The C compiler identification is AppleClang 6.1.0.6020049
-- The CXX compiler identification is AppleClang 6.1.0.6020049
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- …
```
> Include EASTL from the test folder, but allow EASTL to be built separately

- test/packages/EATest/source/EATest.cpp
arguments wasn't closed with va_end() before being reassigned with va_copy() and argumentsSaved wasn't closed at all at the end.
> Close varargs before reassignment with va_copy and after using them

- CMakeLists.txt
Reverts electronicarts/EASTL#38
Reasons:
- The code is untested.
- It doesn't work.
- It would break on Linux if it did work.
> Revert "Allow libs of different configs to be installed in parallel"

- CMakeLists.txt
CMake Error at /usr/local/share/cmake-3.2/Modules/CheckIncludeFiles.cmake:74 (try_compile):
Unknown extension ".c" for file
Adding the C language to the "project" command causes other problems.
The solution was to enable the "C" language explicitly in CMakeLists.txt
enable_language(C)
> Fixed issue where cmake (3.2.2) does not understand its own tests 

- test/CMakeLists.txt
No compiler that I know of on Windows has librt, as such we shouldn't include it.
Verified working.
> Fix linking error on windows when not using msvc.

- include/EASTL/memory.h
MSVC (at least 2013) gives a warning if you store a type with an auto generated destructor in some containers (e.g. vector_set) claiming p is unreferenced. This is clearly a problem from their side but this small change ensures that the code compiles.
> Hack to avoid warning on MSVC

- .travis.yml
This pull request seeks to synchronize the version of CMake used in Travis with that in the CMakeLists.txt.  Travis CI build [here](https://travis-ci.org/electronicarts/EASTL/builds/163357627).
CLA signed last night although there was an interesting redirect to an Adobe login page; not sure that it work.
> Update Travis to use CMake 3.1.3

- include/EASTL/internal/type_pod.h
- test/source/TestTypeTraits.cpp
Fixing an issue in type_traits where is_assignable<T, U> would not be fully defined in MSVC 2013+. For example,  assigning a value of a struct to a ref of a struct of the same type would previously fail.
is_assignable<T,U> et al should now well-defined by utilizing eastl::declval, which should function in MSVC 2013 and later. EASTL_TYPE_TRAIT_is_assignable_CONFORMANCE is now defined, as well.
> Update is_assignable to be well-defined on MSVC 2013+

- include/EASTL/tuple.h
- test/source/TestTuple.cpp
These commits add the typed "get" that was added for tuple in c++14, e.g. items (5)-(7) as described here: http://en.cppreference.com/w/cpp/utility/tuple/get
A couple tests of this are left in in-line with some other simple base tests for the tuple, as well as a small battery of tests specifically for checking some edge cases and each overload of the function.
The "tuple_index" helper was implemented similarly to "tuple_element". It calculates the index by iterating down to the type in question being 'found' in the template list, counting up the index value as it goes. The duplicatetypecheck is used to verify that we have not hit a type before; this allows for protection against a typed access to an ambiguous TupleLeaf. For example, with "tuple<double, double, bool> …
> Adding support for typed get for tuple, e.g. get<typename T>(tuple<Ts...>& t)

- include/EASTL/intrusive_list.h
- test/CMakeLists.txt
This _should_ fix the aliasing issues with intrusive_list on GCC that are seen in release mode. Now all node_types are stored in intrusive_list_nodes, allowing the compiler to pickup on the EASTL_MAY_ALIAS attribute/directive.
> Fix aliasing issues with intrusive_list.

- include/EASTL/iterator.h
- include/EASTL/utility.h
- test/packages/EABase/include/Common/EABase/config/eacompiler.h
These fixes make EASTL usable with VC9 and VC10 (without C++11 support).
> Compatibility with VC9 and VC10

- include/EASTL/vector.h
- test/source/TestVector.cpp
In vector::insert() and vector::set_capacity(), a copy is made on existing elements. Use move semantic in order to avoid copy when elements are moved or vector resize.
Here an example of code which show the extra copy done:
```
struct CheckCopy
{
CheckCopy() : m_Value(0) {}
CheckCopy(int value) : m_Value(value) {}
CheckCopy(const CheckCopy& iOther) : m_Value(iOther.m_Value) { std::cout << "Copy" << std::endl; }
CheckCopy(CheckCopy&& iOther) : m_Value(iOther.m_Value) {}
void operator =(const CheckCopy& iOther) { m_Value = iOther.m_Value; std::cout << "Copy" << std::endl; }
void operator =(CheckCopy&& iOther) { m_Value= iOther.m_Value; }
int m_Value;
};
void TestInsert()
{
eastl::vector<CheckCopy> myVector1;
myVector1.reserve(20);
for (int idx = 0; idx < 2; ++idx) …
```
> Use move instead of copy in vector::insert()/set_capacity()

- .gitignore
- scripts/ci-pre.cmd
- test/packages/EABase/include/Common/EABase/eahave.h
This should speed up the process of the build somewhat.
Quite a significant portion of the time was needing to update gcc and clang to version that wouldn't crash during the build.
Appveyor now runs gcc 5.3 and clang 3.8, clang still needs to be installed, but that's not really slow.
Depends on my previous PR #75.
> Remove the need to update pacman before mingw appveyor builds.

- test/packages/EABase/include/Common/EABase/eabase.h
This commit fixes [issue 47](https://github.com/electronicarts/EASTL/issues/47).
According to [Visual C++ Team Blog](https://blogs.msdn.microsoft.com/vcblog/2013/07/19/c99-library-support-in-visual-studio-2013/), MSVC added C99 library support in Visual Studio 2013.
> Fix C99 inttypes.h macro redefinition warnings with VS2013 and above

- include/EASTL/internal/config.h
- test/packages/EABase/include/Common/EABase/config/eaplatform.h
- test/packages/EATest/include/EATest/EATest.h
The library previously did not recognize Android on ARM64 targets, and did not support breakpoints even if the target were to be recognized. Fixed by adding the required definitions in EABase/config/eaplatform.h, and adding a correct breakpoint instruction to both EASTL and EATest.
> Add support for Android on ARM64

- include/EASTL/utility.h
Because non-ascii characters exist, Visual Studio 2017 Japanese version compiler occurs warning message as below.
> warning C4819: ファイルは、現在のコード ページ (932) で表示できない文字を含んでいます。データの損失を防ぐために、ファイルを Unicode 形式で保存してください。
> Remove Mojibake

- include/EASTL/internal/config.h
Unfortunately this only disables the warning on GCC 7.x. GCC 6.x seems to be
unable to disable this warning.
See Issue #115
> Fix pragma to disable "literal suffix" warning on GCC.

- include/EASTL/vector.h
- test/source/TestVector.cpp
When erase() is called on a vector with an empty range (first == last),
it should be a no-op. If erase() does not check for this case, it can
end up calling the move assignment operator for an obect with itself as
the source and dest. This is unnecessary work at best, and at worst
could cause problems if the object's implementation of the move
assignment does not handle this case well, leaving the object in an
undefined state.
This fix simply adds a check for first==last and avoids doing any work
in that case.
> Check for empty range in vector::erase(first,last)

- include/EASTL/type_traits.h
`IN` is defined to nothing on Win32, it used to be a predecessor to SAL, as described here: https://docs.microsoft.com/en-us/visualstudio/code-quality/best-practices-and-examples-sal
Using `in` instead, allows compilation of EASTL with `clang` on Win32.
> Rename 'IN' to 'in', to avoid compiler errors on windows

- test/packages/EABase/include/Common/EABase/eabase.h
Not defining that ssize_t has already been typedef'ed might upset other libraries trying to define it, too. The `_SSIZE_T_DEFINED` macro is taken from ZeroMQ, since their checking for it. Considering ZeroMQ is a pretty widespread & successfully deployed library, I'd consider using that name safe.
Without it, ZeroMQ fails to compile, due to conflicting types used for ssize_t.
> define _SSIZE_T_DEFINED, when defining typedef ssize_t

- include/EASTL/internal/config.h
Was that done intentionally? Otherwise, feel free to merge the PR.
> EASTL 3.05.09 was released, but the version not bumped

- include/EASTL/optional.h
- test/source/TestOptional.cpp
`optional_storage`, wasn't move constructing `value_type` when passing in an rvalue. The following patch fixes this, `optional` is now properly constructed by moving the optional value in the container, instead of copying it.
Here is a small test case, showing the bug:
```
#include <stdio.h>
#include <EASTL/optional.h>
using namespace eastl;
struct Test {
Test() { printf("Test()\n"); }
Test(Test const &other) noexcept { this->x = other.x; printf("Test(Test const &)\n"); }
Test(Test &&other) noexcept { this->x = other.x; other.x = 0; printf("Test(Test &&)\n"); }
~Test() { printf("~Test() (x = %d)\n", x); }
int x;
};
optional<Test> get_test()
{
Test t;
t.x = 5;
return move(t);
}
int main()
{
auto test = get_test();
if (test)
printf("x = %d\n", test->x);
else
printf("x = ?\n");
}
```
If this …
> Allow move-constructing optional_storage with value_type

- include/EASTL/optional.h
optional.h(42): warning C4574: 'EASTL_EXCEPTIONS_ENABLED' is defined to be '0': did you mean to use '#if EASTL_EXCEPTIONS_ENABLED'?
optional.h(81): warning C4582: 'eastl::Internal::optional_storage<T,false>::val': constructor is not implicitly called
> fix eastl::optional<> MSVC /Wall level 4 warnings

- include/EASTL/numeric.h
If numeric.h included before iterator.h was included it won't compile
on GCC, e.g:
EASTL/numeric.h:132:35: error: expected initializer before ¿<¿ token typedef typename iterator_traits<InputIterator>::value_type value_type;
and Clang, e.g.:
EASTL/numeric.h:159:20: error: expected a qualified name after 'typename'
typedef typename iterator_traits<InputIterator>::value_type value_type;
> fix broken include numeric.h dependency on iterator.h

- include/EASTL/string_view.h
- test/source/TestStringView.inl
string_view.compare method should return non-zero result,
when compare strings with different sizes and same common part.
Added helper static compare function similar to used in string.h.
Fixed string_view compare method using static compare function.
Fixed and added unit tests for string_view.
> fix eastl::string_view compare for string with different sizes

- include/EASTL/string.h
- include/EASTL/vector.h
E.g.:
EASTL/string.h(419): error C2220: warning treated as error - no 'object' file generated
EASTL/string.h(419): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
> fix noexcept warnings in case when compilie with EA_COMPILER_NO_NOEXCEPT

- include/EASTL/tuple.h
Minor Issue. An unused variable in `template<> tuple::swap()` causes issues with Wall & Werror enabled.
> Fix unused variable warning/error in tuple.

- doc/EASTL.natvis
Fixes #154, the bitset natvis wasn't showing correct values.
> Fixing eastl::bitset natvis

- doc/EASTL Best Practices.html
- doc/EASTL FAQ.html
I might be wrong, but it turns out the source code uses `reset_lose_memory()` instead of `reset()` in question?
> Correct the name of container's reset member function

- benchmark/source/BenchmarkSort.cpp
Allowed kSize[] to be updated without requiring manual updates to kSizeCount or kArraySizeMax.
Various sort benchmarks now operate on a vector of sort functions instead of explicitly skipping sort functions in multiple locations.  This change also eliminates the need to handle sort functions in switch statements in order to skip them.
The primary reason for these changes is so that it is easier to benchmark larger array sizes and/or to modify the sort functions that will be benchmarked (since it quickly becomes impractical to benchmark O(n^2) sort functions for larger array sizes).
> Made some changes to the sort benchmark so it is less fragile to other modifications.

- benchmark/source/BenchmarkSort.cpp
Expanded the sorting benchmarks.  The change adds a new RandomizationType and also adds support for radix_sort in the "slow assignment" benchmark.
Additionally this change simplifies some of the radix_sort code so that data can be sorted without first being copied to a temporary buffer and back.
> Radix sort benchmark improvements

- test/packages/EAMain/include/EAMain/EAEntryPointMain.inl
- test/packages/EAMain/include/EAMain/EAMain.h
Note: Some constructors for the CommandLine class still have empty implementations.  However enough of the class has been implemented to be useful on Windows/Unix systems.
> Implemented basic command line handling in EAMain.

- test/packages/EAMain/include/EAMain/EAEntryPointMain.inl
- test/packages/EAMain/include/EAMain/EAMain.h
The variable was previously declared as being static which meant it could take on different values in different translation units.  The issue was resolved by making the variable extern and defining it in EAEntryPointMain.inl (which is assumed to be included exactly once for a program).
> Fixed a bug related to gVerbosityLevel.

- include/EASTL/tuple.h
The lack of inline on these functions was causing some performance problems in some situations where tuple is heavily utilized, often resulting in having to change Cmake's "RelWithDebugInfo" generated configuration in order to get accurate performance data.
e.g. a simple loop over a vector of tuples such as...
```
int numTupleBools = 0;	
for (auto& iter : tupleVec)
{
numTupleBools += get<0>(iter) ? 1 : 0;
}
```
...resulted in nearly twice the number of instructions and execution time, due to having to call eastl::Internal::get(...) on each iteration, instead of accessing the data in the tuple directly.
Note that both of these functions callers and callees have the inline tag, and when "any suitable" inlining is enabled, these functions get inlined away in almost all cases - after all, it …
> Adding "inline" to get(...) functions for TupleImpl

- include/EASTL/type_traits.h
- test/source/TestTypeTraits.cpp
integral_constant<T, v>::value should be constexpr.
This fix use of constexpr non-integral constants, e.g.:
type_traits.h:264:18: error: `constexpr` needed
for in-class initialization of static data member
`int* const eastl::integral_constant<int*, 0u>::value`
of non-integral type [-fpermissive]
> Fix constexpr specifier for integral_constant

- test/packages/EABase/include/Common/EABase/eahave.h
In VS2017 "15.8" changes have been made to the standard library to allow
including some headers, like `<type_traits>`, in completely freestanding (not
linking with msvcp140.dll) mode, so that these may be consumed by the kernel
or similar constrained environments.
Unfortunately this causes problems because the link dependency on the DLL is
injected in yvals.h, so including `<cstddef>` no longer causes _YVALS to be
defined, since that is the header guard for the yvals.h header.
This file is already using _CPPLIB_VER for detection of specific Dinkumware
version, so it's already assuming _CPPLIB_VER indicates Dinkumware, and that
macro is at least pseudo-documented.
> Test for Dinkumware with _CPPLIB_VER instead of _YVALS

- include/EASTL/tuple.h
- test/source/TestTuple.cpp
Additional test cases now check that tuples with move-only ref types now compile properly, instead of, apparently, finding a template deduction that attempted an implicit cast to value-type.
Also, the missing cast of a ValueType& for the TupleLeaf ref specialization was added to satisfy the new test cases.
Fixes #180
> Adding test cases and fixes around move-only/ref types for Tuples

- CMakeLists.txt
Noticed that after moving some headers to 'bonus' that the files were no longer referenced by the EASTL project, due to cmake not including them in the list of sources.
Note that changing the FILE command to use "GLOB_RECURSE" would be done as well, if it was desirable to nab the "internal" headers, but IME I've only ever walked those files as a part of going through 'go to definitions' of files in .../eastl/ or .../eastl/bonus/, and almost never opened up those files directly, as direct project inclusion permits.
> Adding "bonus" headers to files included in EASTL project during cmake generation

- include/EASTL/internal/tuple_fwd_decls.h
- include/EASTL/tuple.h
- test/source/TestTuple.cpp
`const` qualifier on `const tuple_element_t<I, TupleImpl<Indices, Ts...>>&` gets dropped when Ts is an lvalue ref. In this case, the only source of 'const-ness' on `tuple_element_t` comes from being baked into the source type. This means for non-const lvalue refs, the return type just becomes `Ts&`, but `getInternal` will attempt to return a const-ref value, and fail to compile because we cannot remove the const qualifier.
This problem was discovered when trying to use a comparison operator on a tuple containing non-const refs: one of the functions specifically coerces the input parameters to be `const tuple<Ts...>&`, and attempted to then call `get<...>(const tuple<Ts...>&)` on it. This was avoided until a recent experiment because the object used for the input was not strictly const, or …
> Adding tests and fixes for, e.g., comparison of tuples w/ non-const refs

- benchmark/source/BenchmarkSort.cpp
The rationale for adding this is the same as for benchmarking std::sort.  Namely that there should be a benchmark against the std implementations of this sort to ensure the EASTL equivalent of std::stable_sort has competitive performance.
> Added benchmarks for std::stable_sort.

- test/source/TestSort.cpp
The first improvement is to add a sanity check to make sure the sum of the array elements is the same after sorting as before sorting.  Otherwise a sort function that simply zeroed every element in the container could pass the 'is_sorted' test.
The second improvement was to add a test that verifies if the stable sort algorithms are actually stable.
> Improved the sorting tests

- include/EASTL/type_traits.h
- test/source/TestTypeTraits.cpp
Doesn't implement support for mixed-endian (AKA middle-endian): this is in contradiction with how the standard describes how mixed-endian support should behave. I'm assuming that mixed-endian support is not useful for the intended audience of EASTL.
> C++20: type_trait's endian

- include/EASTL/internal/fixed_pool.h
- test/source/TestFixedVector.cpp
While working on some stuff, I noticed that swap() on fixed_vectors with move-only types did not function. This was because the fixed_swap implementation still operated on copy-construction and not move-construction. This update brings the fixed_swap impl back in line to match the functionality in the swap function in utility.h.
> Updating the fixed_pool impl of swap to use Move 

- include/EASTL/string.h
- test/source/TestString.inl
There is no constructor overload that accepts the current arguments.
This can be easily fixed by using the basic_string_view + allocator constructor that already carries the string size.
> Fix basic_string_view sub-string based basic_string constructor

- benchmark/source/BenchmarkSort.cpp
Rationale: small sub-array performance is important because often efficient algorithms such as merge sort and quick sort will revert to using a simple sorting algorithm for small sub-arrays since they are quite often faster for small arrays.
In addition, the CompareSortPerformance function was slightly modified
so that assignment and comparison counts were recorded for the best
performance run of a test instead of the last run.  Some global variables being referenced were also moved into the body of the function.
> Added a new benchmark to better measure the performance of sorting small sub-arrays.

- include/EASTL/bonus/fixed_tuple_vector.h
- include/EASTL/bonus/tuple_vector.h
As suggested here: https://github.com/electronicarts/EASTL/pull/197#discussion_r209438768  This puts the mDataSize member of tuple_vector (used to track how large t_v's allocation itself is) and the mAllocator together into a compressed_pair
> Apply usage of compressed_pair to tuple_vector for empty allocators

- include/EASTL/internal/char_traits.h
- include/EASTL/string.h
- include/EASTL/string_view.h
- scripts/CMake/CommonCppFlags.cmake
- test/packages/EABase/include/Common/EABase/config/eacompiler.h
- test/packages/EABase/include/Common/EABase/config/eacompilertraits.h
A CMake script added GCC-style flags when using clang-cl. This caused an unknown argument warning during compilation.
> Misc build fixes

- include/EASTL/bonus/fixed_tuple_vector.h
- include/EASTL/bonus/tuple_vector.h
- include/EASTL/internal/type_pod.h
- include/EASTL/tuple.h
- test/source/TestFixedTupleVector.cpp
- test/source/TestTuple.cpp
- test/source/TestTupleVector.cpp
This PR resolves "issue"/task https://github.com/electronicarts/EASTL/issues/204 by adding initializer list support to tuple_vector. This includes the following:
- Implementations for the following functions:
```
tuple_vector<Ts...>(std::initializer_list<value_tuple> iList)
operator=(std::initializer_list<value_tuple> iList)
void assign(std::initializer_list<value_tuple> iList)
const_iterator insert(const_iterator pos, std::initializer_list<value_tuple> iList)
```
- ...which are actually all implemented over the following functions, which may be usable for conversion of, say, vectors of tuples into tuple_vectors 😉
```
tuple_vector<Ts...>(const value_tuple* begin, const value_tuple* end)
void assign(const value_tuple* begin, const value_tuple* end)
const_iterator insert(const_iterator pos, …
```
> Adding initializer_list support to tuple_vector (and support for _conditionally_ explicit support for tuple copy/move ctor)

- include/EASTL/bonus/fixed_tuple_vector.h
- include/EASTL/bonus/tuple_vector.h
This was not previously not an issue because the operator= for rvalue-ref of tuple was being invoked implicitly.
This was noticed because tuple_vector::operator=(std::initializer_list<value_tuple> iList) should not have been able to compile. "Assign" for init-list was still being called by other unit-tests, though.
> Fixing issue where tuple_vector::operator= for init-list was not used/compiled

- benchmark/source/BenchmarkAlgorithm.cpp
- include/EASTL/sort.h
This is a fairly minor change, but it gives ~6.5% reduction in time to run the merge_sort/merge_sort_buffer benchmarks on my tests (using MSVC release builds on PC).  The change makes sure that eastl::copy is only invoked once.  Previously copy was called twice even though one of the copies has zero length.  However, this 0 length copy may still have overhead (e.g. calling a non-inline memmove with zero length).
> Optimized the implementation of 'merge' to avoid the overhead of calling copy twice (when only one copy has non-zero length).

- include/EASTL/sort.h
This PR implemented a new variation of merge sort with the ability to call insertion sort for smaller lists as well as optimizations for presorted data.
For random data with inexpensive compare/assignment operations, sort operations typically take only 70-80% of the time.  If data is partially sorted then the performance improvement can be even greater.
For pre-sorted data, this sort is much faster than the previous merge sort implementation.
The new algorithm completes in O(n) time instead of O(n log n) time for sorted data.  For the array sizes in the EASTL benchmarks it is not uncommon to see the sort take only 1-2% of the time as the previous merge sort.
The new algorithm is implemented using a templated class which is currently public.  I could of course put this in an internal …
> Made optimizations to merge_sort.

- include/EASTL/bonus/tuple_vector.h
- include/EASTL/tuple.h
While prepping a standalone version (i.e. only dependency is vanilla STL) of tuple_vector, I ran across a few oddities that could use some minor correcting. These commits fix those up.
Note that commit b8853655a0c06834a49c3a2718ecd2608ddc80b9 is mostly about the slight realization that swap of rvalue tuples is well outside the scope of STL (I mean, in the general case, swapping two rvalues doesn't make any sense, right?) so this constrains the utility of it only to its intended purpose - and location.
> Minor tuple_vector cleanup

- include/EASTL/bonus/fixed_tuple_vector.h
- include/EASTL/bonus/tuple_vector.h
- test/source/TestTupleVector.cpp
Being able to access/copy the allocator has value in some object construction idioms I use and this was missing. Adding an additional `set_allocator()` method would be pretty easy, and I can put that together if we feel there's a need.
> Adding `get_allocator()` method to `tuple_vector` for parity with other containers

- test/packages/EABase/include/Common/EABase/eabase.h
Use `__cpp_char8_t` as a feature check to make sure if `char8_t` is
defined by the compiler it is not redefined.
> Do not define char8_t if it's defined in a C++20 compiler

- test/source/TestOptional.cpp
Provides the fix suggested in #238 
The C++20 draft standard changes the definition of aggregate to exclude types which have any user-declared constructor. In this test source, `local` is no longer an aggregate and thus cannot be aggregate-initialized. However, the defaulted and deleted ctors in this struct are redundant, because the `unique_ptr` member already defaults and deletes the same constructors--so, by default the copy ctor is deleted and the move ctor is defaulted.
> Update test source for C++20 aggregate change

- test/packages/EABase/include/Common/EABase/config/eaplatform.h
Borrowed definitions from Android/iPhone ARM64.
Signed-off-by: Maury Anderson <maury.anderson@rockwellcollins.com>
Signed-off-by: Matthew Weber <matthew.weber@rockwellcollins.com>
> eastl: add support for Linux AArch64

- test/source/TestSList.cpp
- use fixed allocator and pre-defined buffer
> Fix leak in TestSList

- include/EASTL/vector.h
For apps not using exceptions, using noexcept can trigger compilation errors.
> Consistent use of noexcept/EA_NOEXCEPT in vector

- include/EASTL/internal/char_traits.h
Using eastl::string_view in a constexpr context causes a compile error, this fixes #250
> Constexpr String View

- include/EASTL/string.h
With a recent gcc and -Wextra, compiling string.h yields a warning:
EASTL/string.h:3255:55: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
return (currentCapacity <= SSOLayout::SSO_CAPACITY) ? SSOLayout::SSO_CAPACITY : (2 * currentCapacity);
This patch fixes the warning by means of an explicit cast.
> Fix an enumeral/non-enumeral type mix

- include/EASTL/variant.h
The `hash` specialization for monostate had a named parameter (`val`) that wasn't being used by the implementation, and so triggered a C4100 warning under MSVC when compiling with warning level 4 (/W4).
As it's totally unused I just removed the parameter name from the signature rather than using `EA_UNUSED`, for consistency with other PRs (eg. #159).
> Fix unused parameter warning in monostate hash specialization

- include/EASTL/internal/copy_help.h
It's not allowed to call memmove with null pointers even if the size is 0.
In vector::DoInsertValueEnd memmove is called via eastl::uninitialized_move_ptr_if_noexcept unconditionally even for null pointers (when vector is empty).
Therefore, further checks for p in vector::DoFree and allocator::deallocate get optimized away that leads to crashes.
_Maybe_ it's related to this:
https://github.com/electronicarts/EASTL/blob/master/CMakeLists.txt#L58
> Fix UB causing crashes with some compilers.

- include/EASTL/string_hash_map.h
- test/source/TestStringHashMap.cpp
- test/source/main.cpp
Previous implementation always duplicated the key
(even if a previous key already existed).
A leak occurred because the clear was not aware of the
previous key that was discared by the newly duplicated key.
This solution only duplicates a new key if necessary.
> Fix memory leak in string_hash_map::insert_or_assign

- include/EASTL/sort.h
- test/source/TestSort.cpp
Hi!
This is my first PR to EASTL so hello everybody!
I would like to add the `stable_partition` algo in the EASTL.
I added the algo in *Sort.h* and the UT in *TestSort.h*
Let me know if there is some way to launch the unit test on a CI system. I can't test the code on all compiler/OS.
The `stable_partition` is a bit tricky because it is generally done in a way it can be executed even if there is not enough memory.
The version of gcc and msvc, use `get_temporary_buffer` to get the buffer. In the `std`, this function can return **less** memory than requested. That mean that the algo need to handle the case of a buffer smaller than the range to process. This make the algo pretty complicated, but resilient to low memory situation.
**But** I see that in EASTL the `get_temporary_buffer` always …
> Add stable_partition algorithm with unit tests

- include/EASTL/internal/char_traits.h
This fixes a function that triggers C4100 (unreferenced formal parameter) when compiling with MSVC.
> Fix unused parameter warnings in a DecodePart overload

- include/EASTL/variant.h
- test/source/TestMap.cpp
- test/source/TestVariant.cpp
The error message is: forward: none of the 2 overloads could convert all the argument types.
Code to reproduce:
void add(const double e) {variant<double> v{e};}
> Fixed conv ctor and assign op compilation error

- test/source/TestString.cpp
Ignore the long double sprintf test on MinGW-w64 too, this test fails with both clang and gcc.
> "Fix" MinGW-w64 string test failure.

- include/EASTL/chrono.h
...which doesn't seem to be used in any case.
Note that the name and location of this internal header are subject to change without notice, as happened in the Visual Studio 2019 version 16.4 release. *Not* including the header seems to avoid the problem quite nicely ;)
> Avoid non-public header thr/xtimec.h on Win32

- include/EASTL/bitvector.h
- include/EASTL/bonus/tuple_vector.h
- include/EASTL/deque.h
- include/EASTL/span.h
- include/EASTL/vector.h
- include/EASTL/vector_map.h
- include/EASTL/vector_multimap.h
- include/EASTL/vector_multiset.h
- include/EASTL/vector_set.h
Fixing of compilation error when some of `eastl` containers used with `std` types. Reason: ambiguity of `equal()` and `lexicographical_compare()` functions call in overloaded compare operators, which conflicts with its `std` counterparts. So, you can't compare `eastl::vector<std::string>` using `operators==()`, but compare of `eastl::array<std::string>` works fine, because latter use qualified names for its compare operators.
This PR just unifies using of compare functions across all `eastl` containers. So, all unqualified calls to `equal()` and `lexicographical_compare()` functions replaced with quailified ones.
I'm not sure that's a good idea to write tests which can't be compiled in the pre-PR version, so I skipped this part.
Tested on VS 2017 and GCC 7.4
> Using of qualified eastl compare function names

- include/EASTL/internal/config.h
I opened an issue yesterday about gcc 9.2 failed to compile some `constexpr` code in here. https://github.com/electronicarts/EASTL/issues/325
I managed to compile it using clang-9 and investigated into this issue. Unluckily, I have no clue why gcc-9 failed but find out there is a bug in here causing clang will never use `constexpr`.
https://github.com/electronicarts/EASTL/blob/1030ad17b2ca3c74fef36df2e4e490817e81b2cf/include/EASTL/internal/config.h#L150
where the `EA_COMPILER_VERSION` is here 
https://github.com/electronicarts/EABase/blob/d62990dc0a11e0cbc483580d7617ce95ec7a123a/include/Common/EABase/config/eacompiler.h#L341
```
#define EA_COMPILER_VERSION (__clang_major__ * 100 + __clang_minor__)
```
Since clang will define `__GNUC__` and the **EA_COMPILER_VERSION** will be caculated as …
> fix clang never using constexpr

- include/EASTL/shared_ptr.h
- test/source/TestSmartPtr.cpp
atomic_exchange_explicit() for shared_ptr<> doesn't have a return.
> fixed atomic_exchange_explicit() return with shared_ptr<>

- include/EASTL/string_view.h
- test/source/TestStringView.inl
The `find_first_of` overload taking `string_view` parameter was passing the size of `this`, instead of the `sw`'s size, which caused incorrect read of source view's memory.
> Fix string_view::find_first_of buffer overflow bug

- include/EASTL/vector.h
- test/source/TestFixedVector.cpp
Expression
>bMove ? should_move_tag() : should_copy_tag()
wasn't working as expected, basically always coalescenig as
should_copy_tag type (*) which resulted always copy-constructed
code-path to be taken instead of move-contructed's one regardless of
bMove value. Which is perfomance degradation
This code-path e.g. used in fixed_vector's move constructor
(*) You can read more about underlying reasons for this behaviour in
https://stackoverflow.com/questions/8535226/return-type-of-ternary-conditional-operator
> Fix move flavour of vector::DoAssign[FromIterator]

- include/EASTL/iterator.h
- test/source/TestIterator.cpp
Add push_back move (rvalue) flavour in order to code like
eastl::move(container.begin(), container.end(), eastl::back_inserter(container))
to work as intended (which is to use move-version of push_back obviously)
> Fix back_insert_iterator move flavour

- include/EASTL/span.h
- test/source/TestSpan.cpp
Implements the missing `span::front()` and `span::back()` element access members, as well as the `span::subspan()` operation.
Each of the new members follows the same implementation rules used by the existing `span` code and will assert if the user would otherwise invoke undefined behaviour:
* `span::front()` and `span::back()` will assert if the span is empty.
* `span::subspan()` will assert if offset or count exceed the bounds of the span.
Tests are included for each member as follows:
* `span::front()` and `span::back()` are tested along with the existing subscript operator case which I've renamed to TestElementAccess; didn't seem worth putting these in a separate test but calling them subscript operators wasn't really accurate.
* `span::subspan()` tests cases where the range of the …
> Added span::front(), back(), and subspan()

- include/EASTL/iterator.h
Attempted fix for the issue noted in #325 with GCC 9.2.0. Compiling the array tests causes GCC to choke on the subscript operator of reverse_iterator inside of a constant expression.
Using the (commented out) `-n - 1` subscript expression seems to work around this. I can't see anything in the repository history for why it was commented out to begin with, so there might be some implication I'm unaware of, but the tests all still pass under GCC 9.2.0 and Clang 9 for myself at least.
> Fix GCC 9.2 constexpr compile errors in array tests

- include/EASTL/span.h
- test/source/TestSpan.cpp
Fixes #339. The ticket said that rbegin/rend had tests, but this wasn't the case so I've added them as well.
> Fix missing explicit constructors in span::rbegin/rend()

- include/EASTL/internal/enable_shared.h
- test/source/TestSmartPtr.cpp
Add enable_shared_from_this::weak_from_this() because it's now available since C++17.
cf. https://en.cppreference.com/w/cpp/memory/enable_shared_from_this/weak_from_this
> add enable_shared_from_this::weak_from_this() present since C++17

- .travis.yml
- benchmark/CMakeLists.txt
- include/EASTL/internal/char_traits.h
- include/EASTL/string.h
- include/EASTL/string_view.h
- scripts/CMake/CommonCppFlags.cmake
- test/CMakeLists.txt
- test/source/TestString.cpp
- test/source/TestString.inl
- test/source/TestStringView.cpp
* Added `operator ""sv` support for creating a `string_view` from a `char8_t` string literal. Additionally added the `operator ""_sv`to enable testing.
* Added `operator ""s` support for creating a `string` from a `char8_t` string literal.
* Added specializations of `eastl::hash` for both `u8string` and `u8string_view`.
These are only enabled when `char8_t` is a distinct type under C++20, since otherwise the existing `char`-based definitions are sufficient.
* Added test variants for `u8string` and `u8string_view`.
* Added support for some commented-out tests around `wchar_t` support with strings.
Unfortunately there's a number of errors from EAStdC and some other submodules when compiling the full test suite in C++20 mode due to lots of structures and signatures mixing `char` and …
> C++20 char8_t string/string_view support improvements

- include/EASTL/utility.h
- test/source/TestFixedFunction.cpp
Fixes #275.
The referenced issue notes a compilation error that occurs when `fixed_function.h` is included ahead of `functional.h`. This can be demonstrated by just compiling a lone source file with the following:
```cpp
#include <EASTL/fixed_function.h>
```
This results in the following (shortened) inclusion order as dumped via MSVC's `/showIncludes` option, and error:
```
include\EASTL\fixed_function.h
include\EASTL\internal\function_detail.h      # function_detail from fixed_function...
include\EASTL\utility.h                               
include\EASTL\functional.h                  # utility requires reference_wrapper traits...
include\EASTL\internal\mem_fn.h
include\EASTL\internal\function.h
include\EASTL\internal\function_detail.h  # Oops!
include\EASTL\internal\function.h(31): …
```
> Fix circular dependency in fixed_function.h

- include/EASTL/bitvector.h
- test/source/TestBitVector.cpp
use mContainer.begin() instead of &mContainer[0],
since the latter causes out of bounds exception in non release build
> fix bitvector iterators

- include/EASTL/unique_ptr.h
- test/source/TestSmartPtr.cpp
Currently, unique_ptr::reset(), delete the object (if present) and then change the internal pointer.
But, according to standard (see https://en.cppreference.com/w/cpp/memory/unique_ptr/reset), the operation must be done in this order : 
* Saves a copy of the current pointer old_ptr = current_ptr
* Overwrites the current pointer with the argument current_ptr = ptr
* If the old pointer was non-empty, deletes the previously managed object if(old_ptr) get_deleter()(old_ptr).
It make sense, in order to avoid having a internal pointer on an object that will be destroyed.
> fixed unique_ptr::reset() instructions order. Internal pointer must be updated before calling deleting object

- include/EASTL/shared_ptr.h
- test/source/TestSmartPtr.cpp
reset() function of shared_ptr is not thread safe.
It takes so many times to understand/find where come from that memory leak I have in my code. The problem was so difficult to reproduce and isolate!
So here the code:
```
inline void ref_count_sp::release()
{
EASTL_ASSERT((mRefCount > 0) && (mWeakRefCount > 0));
if(Internal::atomic_decrement(&mRefCount) > 0)
Internal::atomic_decrement(&mWeakRefCount);
else
{
free_value();
if(Internal::atomic_decrement(&mWeakRefCount) == 0)
free_ref_count_sp();
}
}
```
If 2 threads, with 2 shared_ptr<> pointed the same value, and are calling the release() function at the same time, the `free_ref_count_sp();` could be not called.
It happens, when thread 1 is calling `Internal::atomic_decrement(&mWeakRefCount);` (due `m_RefCount > 0`) after the thread 2 call …
> eastl::shared_ptr<>::reset(): function not thread safe

- include/EASTL/bonus/adaptors.h
- test/source/TestExtra.cpp
Hello!
When trying the reverse adaptor on a rvalue container:
- There is this  warning on Visual 2015:
`warning C4239: nonstandard extension used : 'argument' : conversion from 'eastl::vector<int,eastl::allocator>' to 'eastl::vector<int,eastl::allocator> &'`
- And this error on Visual2017:
`error C2440: '<function-style-cast>': cannot convert from 'T' to 'eastl::reverse_wrapper<_Ty>'
with
[
T=eastl::vector<int,eastl::allocator>
]
and
[
_Ty=eastl::vector<int,eastl::allocator>
]
`
The member `Container& mContainer;` was wrong because on a lvalue *Container* it is still a reference (example: eastl::vector<int>&), and on a rvalue, it is just a copy (example: eastl::vector<int>) which is fine. So, no need to add a '&' to `Container mContainer;`.
> Fix reverse adaptor when using on a rvalue range

- doc/EASTL.natvis
This change just adds a natvis entry for the `span` class using `eastl::VectorBase` as a template. I've tested in VS2019 and it works as expected.
I've signed the CLA so I think that should be everything required?
> Add eastl::span<*> to EASTL.natvis

- include/EASTL/internal/hashtable.h
- include/EASTL/internal/red_black_tree.h
- test/source/TestMap.h
This PR provides a fix for the `rbtree::emplace_hint()` method, when it called using multiply variadic template arguments. The problem is in `DoInsertValueHint()` method, which can't accept the forwarded parameter pack, expecting an already constructed `pair` only. A small example:
```cpp
eastl::map<int, char> m;
m.emplace(1, 'a'); // ok, arguments are forwarded to the `pair` constructor
m.emplace_hint(m.end(), 2, 'b'); // compilation fail, arguments can't be forwarded
m.emplace_hint(m.end(), eastl::make_pair(2, 'b')); // ok, passing a constructed `pair`
```
This PR makes the interface of the `DoInsertValueHint()` method (internal helper for "hint" versions of insert methods) similar to the `DoInsertValue()` method (another helper for non-"hint" insert methods), so it can be used with …
> rbtree::emplace_hint() compilation fix for variadic arg use

- doc/EASTL.natvis
- include/EASTL/bonus/lru_cache.h
- include/EASTL/internal/atomic/arch/x86/arch_x86_memory_barrier.h
- include/EASTL/internal/config.h
- test/source/TestLruCache.cpp
EASTL: lru_cache iteration tests and added support for initializer_lists
eastl::atomic<T> : fixed msvc compiler warning 4459
> [EASTL 3.17.03]

- include/EASTL/any.h
- include/EASTL/internal/config.h
- include/EASTL/string.h
- include/EASTL/vector.h
- source/red_black_tree.cpp
I was reading through some of the EASTL as a learning exercise and found a few minor typos, grammatical mishaps, or comment style inconsistencies. 
I've fixed them below and corrected the comment style to be more consistent with the rest of the file.
> Minor spelling and grammar corrections.

- include/EASTL/internal/hashtable.h
- include/EASTL/internal/red_black_tree.h
- include/EASTL/utility.h
This PR is similar to #333 in motive. In case of `std` types used as elements of some `eastl` containers, argument-dependent lookup result in `ambiguous call` errors for `move()` and `forward()` calls.
Small example: line `auto [str, flag] = eastl::pair<std::string, bool>("", false);` can't be compiled.
> Using of qualified eastl move() and forward() functions.

- include/EASTL/internal/function_detail.h
Fixed warning C4100: 'functor': unreferenced formal parameter and warning C4100: '<args_0>': unreferenced formal parameter on MSVC with warning level 4.
> Fixed warnings in function_detail.h on MSVC at warning level 4.

- include/EASTL/variant.h
- test/source/TestVariant.cpp
Hello!
The function `eastl::get<T>(variant&&)` can't work because the `get<I>(v)` take a lvalue (*v* has a name so it is a lvalue) and so return a lvalue, which can't be implicitly converted to rvalue.
`eastl::move` is used to force *v* to be a rvalue.
> Fix get<T>(variant) when variant is a rvalue

- include/EASTL/internal/move_help.h
This silences a specific clang-tidy check when using the pass-by-value + move idiom
```cpp
class Foo
{
public:
Foo(eastl::string str)
: m_str{ eastl::move(str) }
{}
private:
eastl::string m_str;
};
```
```
warning: the parameter 'str' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param]
Foo(eastl::string str)
^
const        &
```
With the change introduced with this PR, this warning disappears.
> Removed extra parentheses on eastl::move's return statement

- include/EASTL/sort.h
A bug in the shell_sort algorithm causes a random access iterator to be decremented past begin. Depending on which data structure the iterator points to, decrementing it can trigger memory accesses that are only valid when the iterator is within the correct range. An example of such a data structure is EASTL's deque. This change fixes the algorithm to only decrement the random access iterator when it is valid to do so.
> Fixing heap-buffer-overflow error uncovered by ASan in the [Sort] test.

- test/source/TestAllocator.cpp
Running MSVC's ASan on EASTL's test suite discovered a stack-use-after-scope error due to an incorrect order of construction for certain stack variables. A reference to `buffer1` is used by `intList1`, but `buffer1`'s lifetime is shorter than that of `intList1` because variables are destroyed in reverse order of destruction. The fix is to move the construction of `intList1` after that of `buffer1` to make sure `buffer1` outlives `intList1`.
> Fixing stack-use-after-scope ASan error detected in the [Allocator] test

- include/EASTL/string.h
Hello.
I think I found a bug in MinGW compiler, and EASTL could use a workaround for it.
MinGW cannot handle both zero-size object and variadic arguments
in function signature. If CtorSprintf is empty, variadic arguments of
corresponding string ctor become corrupted. As a result,
eastl::to_string returns random garbage with MinGW compiler.
The workaround is to add unused member into CtorSprintf.
I admit that I couldn't build EASTL tests with my current MinGW setup.
However, this bug was reproduced both on my machine and on machine of the user who reported this bug to me.
This bug reproduces in this example code (which is oversimplified version of string sprintf ctor):
```
#include <cstdio>
#include <cstdarg>
struct Tag1 {};
struct Tag2 { int m; };
void test1(Tag1, const char* pFormat, …
```
> Add workaround for MinGW bug.

- include/EASTL/memory.h
This is a fix for crashes in optimized builds by GCC.
Literally the same bug and the same fix as in #280, just in two more functions
> Fix undefined behavior in memory.h

- include/EASTL/array.h
- test/source/TestArray.cpp
This is based off what has already been done for eastl::pair.
The changes are tested, checking that overriding a bound variable does modify the original array's element, and that the constness is preserved.
> Added structured binding support for eastl::array

- include/EASTL/algorithm.h
- include/EASTL/heap.h
- include/EASTL/sort.h
- test/source/TestSort.cpp
Generalized the use of `eastl::less` in several sorting-related functions. Its usage should be preferred in algorithms, to allow users specializing it for their classes instead of having to define a public operator<.
I've only fixed errors occuring in my specific case; there may be other occurrences elsewhere.
This is also applicable to `eastl::equal_to` (operator==), `eastl::not_equal_to` (operator!=), `eastl::greater` (operator>), `eastl::greater_equal` (operator>=) and `eastl::less_equal` (operator<=). Unless specialized, they all fallback on their respective operator.
> Replaced some generic calls to operator< by eastl::less

- source/assert.cpp
Like some others (#118, #387), I am using EASTL in Windows kernel mode. Some of the default source files such as `assert.cpp` do not compile/work in this context because they require user-mode Windows functions. This PR removes this dependency from `assert.cpp` and provides a default variant for assertion failure in kernel mode.
This needs electronicarts/EABase#4 as prerequisite.
> Add assertion failure variant for win kernel

- test/source/TestUtility.cpp
Use string compare on the object created for the test; not the previously created object.
https://github.com/electronicarts/EASTL/issues/441
> Fix typo in unit test

- include/EASTL/numeric_limits.h
I work on the Visual C++ team, where we regularly build many open-source projects, including EASTL, with development builds of the MSVC compiler and libraries, in order to prevent regressions that would affect projects. This also allows us to provide advance notice of breaking changes, such as this one:
We've merged https://github.com/microsoft/STL/pull/2828, which is removing the declarations of the `_FInf` etc. variables from our headers. This change will ship in VS 2022 17.4 Preview 2, and it breaks EASTL because MSVC's STL still defines `_CPPLIB_VER` (identifying ourselves as Dinkumware-derived sources).
This PR uses our supported macro [`_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE) for identifying the updated versions of MSVC's STL, and instead …
> Avoid using `_FInf` etc. in `numeric_limits.h` after MSVC's STL removes them

- include/EASTL/bonus/tuple_vector.h
Trivial compilation fix for tuple vector used with STD iterator tags.
> Fix missing namespace qualifier in TupleVector.

- include/EASTL/internal/functional_base.h
- test/source/TestFunctional.cpp
It fixes compilation when `eastl::ref(object)` is used as callable object in `eastl::is_invokable`.
Here is code example (unless I messed up because I am writing this code from memory)
```
eastl::function<void()> foo;
constexpr bool v1 = eastl::is_invocable_r_v<void, decltype(eastl::ref(foo))>; // ok
constexpr bool v2 = eastl::is_invocable_r_v<void, decltype(eastl::ref(foo)), int>; // compilation error
```
CppReference also uses `invoke_result` in example implementation.
https://en.cppreference.com/w/cpp/utility/functional/reference_wrapper
> Use invoke_result instead of result_of in reference_wrapper.

- include/EASTL/hash_map.h
- include/EASTL/hash_set.h
It's annoying that default ctors of map and set are explicit, because the following code doesn't compile:
```
struct Test
{
eastl::unordered_map<int, int> m;
};
Test t = {};
```
and I **must** do `m{};`
> Add non-explicit default ctor for hash_map and hash_set.

- .gitignore
- doc/EASTL.natvis
- include/EASTL/algorithm.h
- include/EASTL/internal/config.h
- include/EASTL/internal/fixed_pool.h
- include/EASTL/internal/type_compound.h
- include/EASTL/internal/type_pod.h
- include/EASTL/internal/type_properties.h
- include/EASTL/internal/type_transformations.h
- include/EASTL/type_traits.h
- include/EASTL/unique_ptr.h
- test/source/TestTypeTraits.cpp
- test/source/main.cpp
Changes:
* Fix `fixed_vector_allocator`s copy constructor so it doesn't default construct the overflow allocator.
* Fix a compiler error with the new version of MSBuild related to `__analysis_assume` in combination with lambda captures and function templates.
* Fix natvis visualization of `rbtree_node`.
* Added `is_bounded_array` and `is_unbounded_array` type traits from C++20.
* Update is_trivially_copyable to have all the appropriate integral_constant members.
* make add_pointer::type well specified for cv- or ref-qualified function types. type member evaluates to T (didn't compile previously).
* is_unsigned::value now evaluates to true, to match the standard.
* is_member_pointer::value now evaluates to true for cv-qualified member pointers.
* is_const::value and is_volatile::value can …
> Version 3.20.02.

- include/EASTL/bitvector.h
not only it is same as default implementation, but also disallows move assignment (violates rule-of-5)
since, there is no sense in declaring copy/assignment, we just remove it (use rule of zero) https://en.cppreference.com/w/cpp/language/rule_of_three
> bitvector: remove explicit copy constructor and copy assignment

- CMakeLists.txt
This adds back the install commands that were removed in an earlier commit.
This is the same as #423 but does not include any other changes and is based on the current head commit.
> Re-add install commands

- include/EASTL/variant.h
Some of them are clang-specific (might even require /permissive-), other - msvc.
Example of warning
variant.h(133,24): error: unused parameter 'pThis' [-Werror,-Wunused-parameter]
> variant: fix unused args warnings

- CMakeLists.txt
This adds `EASTL.natvis` to the EASTL target when using MSVC and installs the file to the `doc` directory, enabling users to use the file without needing to reference the Git repository or manually copy the file.
> Add EASTL.natvis to EASTL when using MSVC and install to doc directory

- include/EASTL/bonus/ring_buffer.h
- test/source/TestRingBuffer.cpp
Make sure to compare two ring buffers in ring-buffer-order.
Resolve: https://github.com/electronicarts/EASTL/issues/511 
CC: @grojo-ea @jhopkins-ea
> Fix ring_buffer comparation logic

- include/EASTL/initializer_list.h
The C++ standard does not define how the implementation constructs initializer_list instances from the actual lists. Many compilers seem to use the pointer and size method that EASTL implements, but not MSVC. It uses two pointers (the other obvious way to do it). This PR implements the corresponding constructor to make intializer_list compatible with MSVC.
> Add MSVC support to initializer_list
