electronicarts/EASTL

CMakeLists.txt

Allow libs of different configs to be installed in parallel

---

test/packages/EAStdC/include/EAStdC/EAStopwatch.h

Fix timing numbers for MinGW (issue #50).

---

include/EASTL/internal/type_pod.h
include/EASTL/optional.h

Corrected each 1 character corruption in comment of 2 header files.

Mojibake in EASTL header files. #71

---

.gitignore

Ignores Visual Studio .suo files, Qt Creator .user files,
and the folders generated by the CI scripts.

Ignore IDE and build files.

---

include/EASTL/shared_ptr.h

Corrected the definition of the constructor ref_count_sp to match the declaration

Corrected the constructor of ref_count_sp

---

include/EASTL/algorithm.h
include/EASTL/heap.h
include/EASTL/sort.h
include/EASTL/unique_ptr.h
test/source/ConceptImpls.h
test/source/TestAlgorithm.cpp

Unable to sort non-copy-constructible objects (Issue #92)

---

include/EASTL/bonus/ring_buffer.h

I don't even know if you accept PR's, you certainly don't need to accept this one :)
Just saw how nice your alignment was, and saw a block that looked sad...  and a silly typo

 just some even prettier alignment and a tiny typo in comments fixed

---

include/EASTL/deque.h
test/source/TestDeque.cpp

shrink_to_fit issue#119

---

doc/EASTL FAQ.html

Though I feel like there should be some other argument in favor of 
> The STL has specifications that limit our ability to use it efficiently

minor faq issue fix

---

include/EASTL/string_view.h
test/source/TestStringView.inl

fixes for string_view hash calc implementation

String view hash fixes

---

include/EASTL/string_hash_map.h

converted direct allocate/deallocate calls into EASTLAlloc/Free macros in string_hash_map

---

include/EASTL/sort.h
test/source/TestSort.cpp

This PR adds a test which demonstrates a bug in radix_sort, and also fixes the bug (in a separate commit).

Radix sort test improvements

---

benchmark/source/BenchmarkHash.cpp
benchmark/source/BenchmarkMap.cpp
benchmark/source/BenchmarkSet.cpp
include/EASTL/numeric_limits.h
test/packages/EABase/include/Common/EABase/config/eacompiler.h
test/source/EASTLTest.cpp
test/source/EASTLTest.h

Sadly I missed some of these in https://github.com/electronicarts/EASTL/pull/182

Fix a few more _YVALS -> _CPPLIB_VER.

---

benchmark/source/BenchmarkSort.cpp
test/packages/EAMain/include/EAMain/EAEntryPointMain.inl
test/source/TestTypeTraits.cpp

Fix warnings

---

include/EASTL/sort.h
test/source/TestSort.cpp

This PR adds some optimizations for radix_sort.  The description below comes from the comments in the modified radix_sort implementation.
----
The radix_sort implementation uses two optimizations that are not part of a typical radix sort implementation.
1. Computing a histogram (i.e. finding the number of elements per bucket) for the next pass is done in parallel with the loop that "scatters" elements in the current pass.  The advantage is that it avoids the memory traffic / cache pressure of reading keys in a separate operation. **Note**: It would also be possible to compute all histograms in a single pass.  However, that would increase the amount of stack space used and also increase cache pressure slightly.  However, it could still be faster under some situations.
2. If all elements …

Made a couple radix sort optimizations

---

include/EASTL/internal/type_compound.h
test/source/TestTypeTraits.cpp

C++14: type_trait is_final

---

include/EASTL/optional.h
test/source/TestOptional.cpp

Fix unmached optional value constructor/destructor calls count.
Optional assignment operator should use
value copy constructor instead value assigment operator
if target optional does not contain a value.
If source optional does not contain a value,
target value destructor should be called.

Fix unmached optional value constructor/destructor calls

---

benchmark/source/BenchmarkSort.cpp
test/packages/EAMain/include/EAMain/EAEntryPointMain.inl
test/packages/EAMain/include/EAMain/EAMain.h

Potentially other changes were also eliminated during the 3.10.00 release.  This PR just adds back the changes I noticed were missing.

This commit reintroduces two changes that were accidentally lost during

---

CONTRIBUTING.md

I added some documentation about building benchmarks after this issue was created:
https://github.com/electronicarts/EASTL/issues/218
Hopefully adding these docs will make it easier and more obvious for people contributing to the project.

Added some notes about generating projects with support for benchmarks.

---

include/EASTL/any.h
test/source/TestAny.cpp

Adding unsafe cast operations.
Please review.

adding unsafe any cast operations

---

include/EASTL/internal/hashtable.h

In some cases calculation a hash can be expensive and application can already have it calculated.
This doesn't change any public API functions, but allows external application to save some performance
by using already caclulated hash in their own hashmap/hashset implementation based on internal EASTL 'hashtable' container

Hashtable external key

---

include/EASTL/optional.h

This caused a compilation error when compiling with exceptions enabled.

Add a missing include to optional.h

---

README.md

Add description of Conan package manager and EASTL availability there.
/cc @danimtb

Add Conan to package managers

---

include/EASTL/bonus/tuple_vector.h
test/source/TestTupleVector.cpp

Fix tuple vector assign

---

include/EASTL/string.h

Old implementation confused GCC 9 (reproduced on 9.1.1 & 9.3.1, not
reproduced on earlier versions) on string assigment of
exact SSO_CAPACITY (23) length. It caused
SSO string to be non-terminated and further segfault on attempt
to interpret actual string content as pointers data (i.e. heap string)
New propsed implementation works with all major compilers including
GCC, MSVC & Clang (tested both normal & sanitized builds in fairly
large commertial project)
Note on implementation:
* Don't memset whole string in default ctor anymore (as for empty
initialized SSO string we don't need to change anything besides
first null-terminated character & mnRemainingSize) - this should
save a few cycles on default string ctor which is quite frequently
executing code
* AllocateSelf(size_type n) now sets …

Fix GCC 9 string SSO segfault

---

include/EASTL/deque.h

Imporantant -> Important.
thats all

Fixed typo in Deque comments

---

.github/workflows/c-cpp.yml

Adding Github Actions CI to EASTL repository.

Creating github actions workflow

---

.github/workflows/c-cpp.yml
CMakeLists.txt
benchmark/CMakeLists.txt
test/CMakeLists.txt

Test to add `EASTL_STD_ITERATOR_CATEGORY_ENABLED` to the matrix of things that get tested under ci.

Test ci for iterator categories

---

test/source/TestLruCache.cpp

This should fix https://github.com/electronicarts/EASTL/issues/498

Add a const to an equality operator to make P2468R2 happy.

---

include/EASTL/array.h
include/EASTL/internal/type_transformations.h
include/EASTL/span.h

remove accidental references to std library
